### ISSUE TITLE
Example with 'app' directory? 

### ISSUE THREAD

**Issue by jakeisnt** [leerob/nextjs-multiple-domains#1]
Hey,

Trying to figure out how to handle multiple domains with the app directory. Any tips? getServerSideProps isn't an option there.

**Comment by matbrgz** [comment]
Hi Jake @jakeisnt ,

I noticed you were exploring how to handle multiple domains using the Next.js app directory and mentioned that getServerSideProps isn't available there. Were you able to find a solution to this problem? If so, could you please share how you resolved it? I'd greatly appreciate any insights or tips you might have.

Thanks in advance!

**Comment by jakeisnt** [comment]
> Hi Jake @jakeisnt ,
> 
> 
> 
> I noticed you were exploring how to handle multiple domains using the Next.js app directory and mentioned that getServerSideProps isn't available there. Were you able to find a solution to this problem? If so, could you please share how you resolved it? I'd greatly appreciate any insights or tips you might have.
> 
> 
> 
> Thanks in advance!

Didn't find a solution -- XSS makes this especially hard. Used a different single-domain product strategy instead
